CREATE DATABASE CarRentalSystem

USE CarRentalSystem

CREATE TABLE CUSTOMER
(
CUST_ID INT PRIMARY KEY IDENTITY(1,1),
CUST_CNIC VARCHAR(13) UNIQUE NOT NULL,
CUST_NAME VARCHAR(50) NOT NULL,
CUST_AGE INT NOT NULL,
CUST_CONTACT VARCHAR(11) NOT NULL,
CUST_ADDRESS VARCHAR(200) NOT NULL
);


CREATE TABLE CARTYPE
(
CTYPE_ID INT PRIMARY KEY IDENTITY(1,1),
CTYPE_TYPE VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE CARMAKE
(
CMAKE_ID INT PRIMARY KEY IDENTITY(1,1),
CMAKE_NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE CARMODEL
(
CMODEL_ID INT PRIMARY KEY IDENTITY(1,1),
CMAKE_ID INT FOREIGN KEY REFERENCES CARMAKE(CMAKE_ID),
CMODEL_NAME VARCHAR(50) UNIQUE NOT NULL,
CTYPE_ID INT FOREIGN KEY REFERENCES CARTYPE(CTYPE_ID)
);

CREATE TABLE CAR
(
C_ID INT PRIMARY KEY IDENTITY(1,1),
C_REGNO VARCHAR(10) UNIQUE NOT NULL,
CMODEL_ID INT FOREIGN KEY REFERENCES CARMODEL(CMODEL_ID),
CTYPE_TYPE VARCHAR(50) FOREIGN KEY REFERENCES CARTYPE(CTYPE_TYPE),
[STATUS] VARCHAR(20) NOT NULL 
);

CREATE TABLE CARRENT
(
CR_ID INT PRIMARY KEY IDENTITY(1,1),
C_ID INT FOREIGN KEY REFERENCES CAR(C_ID),
CR_RENT INT NOT NULL,
CR_SDEPOSIT INT NOT NULL
);

CREATE TABLE CARRENTAL
(
CRENTAL_ID INT PRIMARY KEY IDENTITY(1,1),
CR_ID INT FOREIGN KEY REFERENCES CARRENT(CR_ID),
CRENTAL_HIREDATE DATE NOT NULL,
CRENTAL_RETURNDATE DATE NOT NULL,
CRENTAL_REQUIREDFOR INT NOT NULL,
CUST_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUST_ID),
CRENTAL_STATUS VARCHAR(20) NOT NULL
);


CREATE TABLE IMANAGER
(
M_UN NVARCHAR(50) PRIMARY KEY ,
M_NAME VARCHAR(30) NOT NULL,
M_AGE INT NOT NULL,
M_CONTACT VARCHAR(20) UNIQUE NOT NULL,
M_PASSWORD VARCHAR(50) NOT NULL,
);
CREATE TABLE BMANAGER
(
BM_UN NVARCHAR(50) PRIMARY KEY ,
BM_NAME VARCHAR(30) NOT NULL,
BM_AGE INT NOT NULL,
BM_CONTACT VARCHAR(20) UNIQUE NOT NULL,
BM_PASSWORD VARCHAR(50) NOT NULL,
);
insert into BMANAGER values('hasan126','Hasan Qadeer',21,'+923332922126','hasan')
insert into IMANAGER values('saad1','Saad Ahmed Khan',21,'+928368487344','saad')

